### ISSUE TITLE
Urgent Alarm "alarmTimeagoWarn"

### ISSUE THREAD

**Issue by jokellerweb** [jotomo/AndroidAPS#28]
During the night (19.12.2017 23:59)  there was an urgent alarm "check pump time". I checked pump and phone, times were identical. The error did not repeat. Enclosed the logfile

[AndroidAPS._2017-12-19_PumpTimeError.log](https://github.com/jotomo/AndroidAPS/files/1574689/AndroidAPS._2017-12-19_PumpTimeError.log)

**Comment by jotomo** [comment]
The Combo shows the message `Pump clock update needed` if the pump's time is off.
The `alarmTimeagoWarn` is a warning from Nightscout (preferences _NSClient_, _Alarm options_). Probably the _urgent stale data_ alarm? (I use AAPS' local alerts and xDrip alerts, but no NS alerts myself).
So I'd speculate there was a (temporary) issue uploading data to Nightscout? I think NS alarm settings are fetched once and then triggered locally by AAPS.

**Comment by AdrianLxM** [comment]
@jokellerweb "check pump time" is nothing coming from AndroidAPS. AndroidAPS say "Pump clock update needed"  (`MainApp.sResources.getString(R.string.combo_notification_check_time_date)`)

If you see the text it might be an outdated version or a String pushed from Nightscout.

I'd recommend the following:
 * Make sure you have an up to date AndroidAPS
 * Use the local alarms instead of the Nightscout alarms.

**Comment by jokellerweb** [comment]
Android APS is up to date. I use local alams of xdrips, all nightscout alarms are off. 

I have no SIM card in my phone. Without wlan everything goes fine. can bad wifi (on / off in constant change) cause problems with multiple messages? When the mistake occurred yesterday, I had a bad wifi.

**Comment by AdrianLxM** [comment]
The up-to-date version of AndroidAPS does not have the string "check pump time" in the code.

**Comment by AdrianLxM** [comment]
That it only happens when you are on WIFI is another hint, that the alarm is originated from an online source and not from AndroidAPS
