### ISSUE TITLE
Setting TempTarget and changing profile, then deleting old profil, caused automated, very strange profile changes 

### ISSUE THREAD

**Issue by Heiner1** [jotomo/AndroidAPS#45]
Happened one time at about 2018-01-11_15-02-00  while preparing for cycling; result was an urgent alarm, because value DIA was automatically deleted, and other values had been changed: 
15:02:51.059 [pool-3-thread-1] ERROR [info.nightscout.androidaps.plugins.OpenAPSAMA.OpenAPSAMAPlugin:290]: Value dia is out of hard limits.
0.00 limited to 2.00  
Look at cutted logfile and AAPS screenshot.

[AAPS-Combotest-vanished-LP-entries.txt](https://github.com/jotomo/AndroidAPS/files/1630575/AAPS-Combotest-vanished-LP-entries.txt)

![screenshot_20180111-150449-crazy-lp-issue](https://user-images.githubusercontent.com/20724321/34929614-260e3f34-f9c5-11e7-8e87-86c0561d3160.png)

Till now I was not able to reproduce this.

**Comment by jotomo** [comment]
@MilosKozak This might be made worse by the Combo, since profile updates on the pump take quiet long, but codewise this should be unrelated to the Combo. (I've seen that too at some point, but thought it was probably local to my in-development version). Any idea? The user-set profile shouldn't be touched when doing profile switches (percentage/shifts with a single profile), right?

**Comment by jotomo** [comment]
@Heiner1 I haven't heard of any more occurrences of this bug, so I'm assuming it was fixed when Milos changed the code around profile handling. Please re-open if you encounter this again.

**Comment by Heiner1** [comment]
It didn't occurre at my apps since that time. Thanks for closing. I thaught the same but have not the full bug overview.
